<a href="https://colab.research.google.com/github/akshita123454/mineral-exploration-cps/blob/main/ndvi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install earthengine-api geemap

Requirement already satisfied: earthengine-api in /usr/local/lib/python3.12/dist-packages (1.7.22)
Requirement already satisfied: geemap in /usr/local/lib/python3.12/dist-packages (0.37.2)
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.12/dist-packages (from earthengine-api) (3.10.1)
Requirement already satisfied: google-api-python-client>=1.12.1 in /usr/local/lib/python3.12/dist-packages (from earthengine-api) (2.194.0)
Requirement already satisfied: google-auth>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from earthengine-api) (2.47.0)
Requirement already satisfied: google-auth-httplib2>=0.0.3 in /usr/local/lib/python3.12/dist-packages (from earthengine-api) (0.3.1)
Requirement already satisfied: httplib2<1dev,>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from earthengine-api) (0.31.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from earthengine-api) (2.32.4)
Requirement already satisfied: anywidget in /usr/local/lib/python3.12/dist-packages (from geemap) (0.9.21)
Requirement already satisfied: bqplot in /usr/local/lib/python3.12/dist-packages (from geemap) (0.12.45)
Requirement already satisfied: eerepr>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from geemap) (0.1.2)
Requirement already satisfied: folium>=0.17.0 in /usr/local/lib/python3.12/dist-packages (from geemap) (0.20.0)
Requirement already satisfied: geocoder in /usr/local/lib/python3.12/dist-packages (from geemap) (1.38.1)
Requirement already satisfied: ipyevents in /usr/local/lib/python3.12/dist-packages (from geemap) (2.0.4)
Requirement already satisfied: ipyfilechooser>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from geemap) (0.6.0)
Requirement already satisfied: ipyleaflet>=0.19.2 in /usr/local/lib/python3.12/dist-packages (from geemap) (0.20.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from geemap) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from geemap) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from geemap) (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from geemap) (5.24.1)
Requirement already satisfied: pyperclip in /usr/local/lib/python3.12/dist-packages (from geemap) (1.11.0)
Requirement already satisfied: pyshp>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from geemap) (3.0.3)
Requirement already satisfied: python-box in /usr/local/lib/python3.12/dist-packages (from geemap) (7.4.1)
Requirement already satisfied: scooby in /usr/local/lib/python3.12/dist-packages (from geemap) (0.11.2)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium>=0.17.0->geemap) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium>=0.17.0->geemap) (3.1.6)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from folium>=0.17.0->geemap) (2026.3.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.12.1->earthengine-api) (2.30.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.12.1->earthengine-api) (4.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.4.1->earthengine-api) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.4.1->earthengine-api) (4.9.1)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1dev,>=0.9.2->earthengine-api) (3.3.2)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (from ipyfilechooser>=0.6.0->geemap) (7.7.1)
Requirement already satisfied: jupyter-leaflet<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from ipyleaflet>=0.19.2->geemap) (0.20.0)
Requirement already satisfied: traittypes<3,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from ipyleaflet>=0.19.2->geemap) (0.2.3)
Requirement already satisfied: psygnal>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from anywidget->geemap) (0.15.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from anywidget->geemap) (4.15.0)
Requirement already satisfied: traitlets>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from bqplot->geemap) (5.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->geemap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->geemap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->geemap) (2026.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from geocoder->geemap) (8.3.3)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from geocoder->geemap) (1.0.0)
Requirement already satisfied: ratelim in /usr/local/lib/python3.12/dist-packages (from geocoder->geemap) (0.1.6)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from geocoder->geemap) (1.17.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage->earthengine-api) (2.5.1)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage->earthengine-api) (2.8.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage->earthengine-api) (1.8.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->earthengine-api) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->earthengine-api) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->earthengine-api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->earthengine-api) (2026.4.22)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->geemap) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->geemap) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->geemap) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->geemap) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->geemap) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->geemap) (11.3.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->geemap) (9.1.4)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.12.1->earthengine-api) (1.74.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.12.1->earthengine-api) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.12.1->earthengine-api) (1.27.2)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.6.10)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (7.34.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.0.16)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium>=0.17.0->geemap) (3.0.3)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->earthengine-api) (0.6.3)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ratelim->geocoder->geemap) (4.4.2)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.5.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (75.2.0)
Collecting jedi>=0.16 (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap)
  Downloading jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.9.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.5.7)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.8.6)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (5.9.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (25.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (7.17.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.25.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.3.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.6.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.9.6)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.26.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.4.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.30.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.14.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.8.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.0)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.13.0)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.5.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (7.7.0)

In [1]:
import ee
import geemap

ee.Authenticate()
ee.Initialize(project = 'mineral-exploration-project')

In [ ]:

from google.colab import files

uploaded = files.upload()

In [ ]:
import pandas as pd

df = pd.read_csv('elev_and_slope.csv')

In [ ]:
cols_to_keep = [
    'latitude',
    'longitude',
    'elevation',
    'slope',
    'country',
    'state',
    'ore',
    'gangue',
    'dep_type',
    'hrock_type',
    'arock_type',
    'ore_ctrl',
    'commod1'
]

df_clean = df[cols_to_keep].copy()

In [ ]:
df_clean.to_csv('elev_and_slope_clean.csv', index=False)

In [ ]:
from google.colab import files
files.download('elev_and_slope_clean.csv')

In [ ]:

from google.colab import files

uploaded = files.upload()

In [ ]:
import pandas as pd

df = pd.read_csv('elev_and_slope_clean.csv')

In [8]:
# See all unique countries in dataset

countries = df['country'].dropna().unique()

print(countries)

['United States' 'Argentina' 'Ghana' 'Oman' 'Angola' 'Namibia' 'Botswana'
 'Indonesia' 'China' 'Gabon' 'Kenya' 'Algeria' 'Burma'
 'Congo (Brazzaville)' 'Egypt' 'India' 'Korea, South' 'Iran' 'Israel'
 "Cote D'Ivoire" 'Morocco' 'Malaysia' 'Mozambique' 'Pakistan'
 'Philippines' 'Tanzania' 'Mali' 'Turkey' 'Peru' 'Bolivia' 'Mexico'
 'Canada' 'Costa Rica' 'Russia' 'Brazil' 'Kazakhstan' 'Germany' 'Slovenia'
 'Austria' 'France' 'United Kingdom' 'Spain' 'Tunisia' 'Zimbabwe'
 'South Africa' 'Australia' 'Azerbaijan' 'Sweden' 'Norway' 'Bulgaria'
 'Hungary' 'Western Sahara' 'Burkina Faso' 'Uganda' 'New Zealand'
 'Denmark' 'Somalia' 'Mauritania' 'Niger' 'Senegal' 'Sierra Leone' 'Togo'
 'Zambia' 'Cyprus' 'Iraq' 'Japan' 'Jordan' 'Taiwan' 'Thailand' 'Guinea'
 'Congo (Kinshasa)' 'Mongolia' 'Guatemala' 'Poland' 'Laos' 'Italy'
 'Guyana' 'Jamaica' 'Venezuela' 'Fiji' 'Suriname' 'Cameroon'
 'Solomon Islands' 'Ireland' 'Malawi' 'Afghanistan' 'Finland' 'Sri Lanka'
 'Chile' 'Bosnia and Herzegovina' 'Montenegro' 'Libya' 'Saudi Arabia'
 'Uzbekistan' 'Greece' 'Ecuador' 'Serbia' 'Ethiopia' 'Slovakia' 'Albania'
 'Czech Republic' 'Romania' 'Ukraine' 'Macedonia' 'Colombia' 'Cuba'
 'Burundi' 'Korea, North' 'Syria' 'Estonia' 'Nauru' 'Portugal'
 'Papua New Guinea' 'Georgia' 'Tajikistan' 'Kyrgyzstan' 'Armenia'
 'Madagascar' 'Swaziland' 'Honduras' 'Haiti' 'Dominican Republic' 'Sudan'
 'Panama' 'Belize' 'El Salvador' 'Nicaragua' 'Uruguay'
 'Saint Kitts and Nevis' 'Saint Vincent and the Grenadines' 'Saint Lucia'
 'Dominica' 'Antigua and Barbuda' 'Bahamas, the' 'Bahamas, The'
 'Netherlands' 'Barbados' 'Paraguay' 'Cambodia' 'Vietnam' 'Lesotho'
 'Liberia' 'Vanuatu' 'Palau' 'Antarctica' 'Rwanda' 'Croatia'
 'Turkmenistan' 'Nigeria' 'Belgium' 'Belarus' 'Qatar' 'Benin' 'Bangladesh'
 'Nepal' 'Lebanon' 'Switzerland' 'Luxembourg' 'United Arab Emirates'
 'Singapore' 'Lithuania' 'Trinidad and Tobago' 'Bahrain' 'Gambia, the'
 'Iceland' 'Russia, Kazakhstan']

In [4]:
import pandas as pd

df = pd.read_csv('elev_and_slope_clean.csv')
df.head(5)

,latitude,longitude,elevation,slope,country,state,ore,gangue,dep_type,hrock_type,arock_type,ore_ctrl,commod1
0,55.05612,-132.14344,417.0,34.061240,United States,Alaska,"Chalcopyrite, Covellite, Pyrite","Quartz, Sericite",NaN,Schist,NaN,NaN,Copper
1,55.52751,-132.68514,773.0,29.553010,United States,Alaska,"Chalcopyrite, Pyrite","Calcite, Quartz, Siderite",NaN,Diabase,NaN,Vein Follows Contact,Copper
2,55.97751,-132.99906,58.0,3.311626,United States,Alaska,"Chalcopyrite, Pyrite, Sphalerite",Quartz,NaN,Siltstone,NaN,NaN,Copper
3,55.52195,-132.68653,653.0,20.563173,United States,Alaska,"Galena, Malachite, Pyrite",NaN,NaN,Granite,Granite,NaN,Gold
4,55.14556,-132.05233,36.0,8.804730,United States,Alaska,Pyrite,NaN,NaN,Mica Schist,NaN,NaN,Gold

In [12]:
nearby_countries = [
    'India',
    'Pakistan',
    'Bangladesh',
    'Nepal',
    'Sri Lanka',
    'Burma',   # Myanmar in your dataset
    'China'
]

df_region = df[df['country'].isin(nearby_countries)]

print(df_region.shape)
df_region.head()

(3582, 13)

,latitude,longitude,elevation,slope,country,state,ore,gangue,dep_type,hrock_type,arock_type,ore_ctrl,commod1
3639,18.61144,109.30263,227.0,5.878424,China,Liaoning,NaN,NaN,NaN,Dolomite,NaN,Mn-Bearing Searies,Manganese
3729,41.93420,93.00833,925.0,3.046159,China,Xinjiang* [Sinkiang],NaN,NaN,NaN,NaN,NaN,NaN,Manganese
3754,40.40652,108.40366,1242.0,9.575106,China,Nei Mongol* (Inner Mongolia),NaN,NaN,NaN,NaN,NaN,NaN,Manganese
3805,32.20980,114.50770,65.0,2.379133,China,Hunan,NaN,NaN,NaN,NaN,NaN,NaN,Manganese
3806,26.30470,118.51181,428.0,30.695847,China,Fujian [Fukien],NaN,NaN,NaN,NaN,NaN,NaN,Manganese

In [14]:
# Remove invalid rows
df_region = df_region.dropna(subset=['latitude', 'longitude'])

# Convert to numeric (in case of strings)
df_region['latitude'] = pd.to_numeric(df_region['latitude'], errors='coerce')
df_region['longitude'] = pd.to_numeric(df_region['longitude'], errors='coerce')

# Drop again after conversion
df_region = df_region.dropna(subset=['latitude', 'longitude'])

# Remove invalid ranges
df_region = df_region[(df_region['latitude'] >= -90) & (df_region['latitude'] <= 90)]
df_region = df_region[(df_region['longitude'] >= -180) & (df_region['longitude'] <= 180)]

df_region.reset_index(drop=True, inplace=True)

print("Cleaned dataset size:", len(df_region))

Cleaned dataset size: 3582

In [15]:
df_region.to_csv('elev_and_slope_india.csv', index=False)

In [16]:
from google.colab import files
files.download('elev_and_slope_india.csv')

In [17]:
from google.colab import files

uploaded = files.upload()

Saving elev_and_slope_india.csv to elev_and_slope_india (1).csv

In [50]:
import pandas as pd

df = pd.read_csv('elev_and_slope_india.csv')

In [51]:
sentinel = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')

In [52]:
def get_ndvi_image(lat, lon):
    point = ee.Geometry.Point([lon, lat])

    image = (sentinel
             .filterBounds(point)
             .filterDate('2019-01-01', '2021-12-31')
             .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20))
             .median())

    ndvi = image.normalizedDifference(['B8', 'B4']).rename('NDVI')

    return ndvi.sample(point, 10).first().get('NDVI')

In [53]:
def df_to_ee(df):
    features = []
    for i in range(len(df)):
        lat = df.iloc[i]['latitude']
        lon = df.iloc[i]['longitude']

        point = ee.Geometry.Point([lon, lat])
        feature = ee.Feature(point, {
            'Latitude': lat,
            'Longitude': lon
        })

        features.append(feature)

    return ee.FeatureCollection(features)

In [54]:
image = (sentinel
         .filterDate('2019-01-01', '2021-12-31')
         .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20))
         .median())

ndvi_image = image.normalizedDifference(['B8', 'B4']).rename('NDVI')

In [55]:
def get_ndvi_fc(fc):
    return ndvi_image.sampleRegions(
        collection=fc,
        scale=10,
        geometries=False   # 🔥 VERY IMPORTANT FIX
    )

In [56]:
import pandas as pd

def ee_to_df(fc):
    features = fc.getInfo()['features']

    data = []
    for f in features:
        props = f['properties']
        data.append(props)

    return pd.DataFrame(data)

In [57]:
batch_size = 1000

results = []

for i in range(0, len(df), batch_size):

    print(f"Processing batch {i} to {i+batch_size}")

    batch = df.iloc[i:i+batch_size]

    fc = df_to_ee(batch)

    ndvi_fc = get_ndvi_fc(fc)

    ndvi_df = geemap.ee_to_df(ndvi_fc)

    results.append(ndvi_df)

Processing batch 0 to 1000
Processing batch 1000 to 2000
Processing batch 2000 to 3000

WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

Processing batch 3000 to 4000

WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

In [58]:
ndvi_full = pd.concat(results)

ndvi_full.head()

   Latitude  Longitude      NDVI
0  18.61144  109.30263  0.684521
1  41.93420   93.00833  0.053832
2  40.40652  108.40366  0.155052
3  32.20980  114.50770  0.350995
4  26.30470  118.51181  0.784119

In [62]:
ndvi_full = ndvi_full.groupby(
    ['Latitude', 'Longitude'],
    as_index=False
)['NDVI'].mean()

In [64]:
final_df = df.merge(
    ndvi_full[['Latitude', 'Longitude', 'NDVI']],
    left_on=['latitude', 'longitude'],
    right_on=['Latitude', 'Longitude'],
    how='left'
)
final_df.head()
print(len(final_df))

3582

In [65]:
final_df.drop(columns=['Latitude', 'Longitude'], inplace=True)

In [67]:
final_df.to_csv('india_elev_slope_ndvi.csv', index=False)

In [68]:
from google.colab import files
files.download('india_elev_slope_ndvi.csv')